/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.simercandetc.Vista;

import com.mycompany.simercandetc.Controlador.ControladorVistaNota;
import com.mycompany.simercandetc.Dao.NotaDao;
import com.mycompany.simercandetc.Modelo.Nota;
import java.time.LocalDate;
import java.util.List;
import javax.swing.JTextField;

/**
 *
 * @author Admin
 */
public class VistaNotas extends javax.swing.JFrame {

    /**
     * Creates new form VistaNotas
     */private int posL=0;
        
    public VistaNotas() {
        initComponents();
        txtDesc.setLineWrap(true);
        txtDesc.setWrapStyleWord(true);
        jtDescripcion.setLineWrap(true);
        jtDescripcion.setWrapStyleWord(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtTitulo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtDescripcion = new javax.swing.JTextArea();
        jDFecha = new com.toedter.calendar.JDateChooser();
        btnGuardar = new javax.swing.JButton();
        btnVerGuardados = new javax.swing.JButton();
        idU = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDesc = new javax.swing.JTextArea();
        txtTitulo = new javax.swing.JLabel();
        btnSig = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("DESCRIPCION:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 80, -1));

        jLabel2.setText("FECHA:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 80, -1));

        jLabel3.setText("TITULO:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 80, -1));

        jtTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtTituloActionPerformed(evt);
            }
        });
        jPanel1.add(jtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 340, -1));

        jtDescripcion.setColumns(20);
        jtDescripcion.setRows(5);
        jScrollPane1.setViewportView(jtDescripcion);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 340, 130));

        jDFecha.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(jDFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, 170, -1));

        btnGuardar.setBackground(new java.awt.Color(0, 204, 0));
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 460, 120, -1));

        btnVerGuardados.setText("VER GUARDADOS");
        jPanel1.add(btnVerGuardados, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 460, 130, -1));
        jPanel1.add(idU, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 30, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtDesc.setBackground(new java.awt.Color(240, 240, 240));
        txtDesc.setColumns(20);
        txtDesc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDesc.setRows(5);
        jScrollPane2.setViewportView(txtDesc);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 280, 200));

        txtTitulo.setBackground(new java.awt.Color(255, 255, 204));
        txtTitulo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 260, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 110, 300, 310));

        btnSig.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSig.setText("---->");
        btnSig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSigActionPerformed(evt);
            }
        });
        jPanel1.add(btnSig, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 430, -1, -1));

        btnAtras.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAtras.setText("<----");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        jPanel1.add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 430, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -3, 1097, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtTituloActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String ttl=jtTitulo.getText();
        String fecha =((JTextField)jDFecha.getDateEditor().getUiComponent()).getText();
        int id= Integer.parseInt(idU.getText());
        String desc= jtDescripcion.getText();
        
        ControladorVistaNota ctrlvN= new ControladorVistaNota();
        ctrlvN.guardar(ttl,desc,fecha,id);
        
        jtTitulo.setText("");
        jtDescripcion.setText("");
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnSigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSigActionPerformed
        posL+=1;
        txtTitulo.setText("");
        txtDesc.setText("");
        
        int id=Integer.parseInt(idU.getText());
        String titulo ="";
        String desc="";
        NotaDao nDao= new NotaDao();
        LocalDate fecha = LocalDate.now();
        
        String fech = String.valueOf(fecha);
        List<Nota> lista = nDao.recordatorio(id, fech);
        for (int i = 0; i < lista.size(); i++) {
            titulo = lista.get(posL).getTitulo();
            desc = lista.get(posL).getDescripcion();
        }
        int num = lista.size();
        num-=1;
        txtTitulo.setText(titulo);
        txtDesc.setText(desc);
        
        btnAtras.setVisible(true);
        if(posL==num){
            btnSig.setVisible(false);
        }else{
            btnSig.setVisible(true);
        }

    }//GEN-LAST:event_btnSigActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        posL-=1;
        txtTitulo.setText("");
        txtDesc.setText("");
        
        int id=Integer.parseInt(idU.getText());
        String titulo ="";
        String desc="";
        NotaDao nDao= new NotaDao();
        LocalDate fecha = LocalDate.now();
        
        String fech = String.valueOf(fecha);
        List<Nota> lista = nDao.recordatorio(id, fech);
        for (int i = 0; i < lista.size(); i++) {
            titulo = lista.get(posL).getTitulo();
            desc = lista.get(posL).getDescripcion();
        }
        
        txtTitulo.setText(titulo);
        txtDesc.setText(desc);
        if(posL==0){
            btnAtras.setVisible(false);
        }else{
            btnAtras.setVisible(true);
        }
        btnSig.setVisible(true);
    }//GEN-LAST:event_btnAtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaNotas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAtras;
    public javax.swing.JButton btnGuardar;
    public javax.swing.JButton btnSig;
    public javax.swing.JButton btnVerGuardados;
    public javax.swing.JTextField idU;
    public com.toedter.calendar.JDateChooser jDFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTextArea jtDescripcion;
    public javax.swing.JTextField jtTitulo;
    public javax.swing.JTextArea txtDesc;
    public javax.swing.JLabel txtTitulo;
    // End of variables declaration//GEN-END:variables
}
