/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.simercandetc.Vista;

import com.mycompany.simercandetc.Controlador.ControladorVistaDesCorreo;
import com.mycompany.simercandetc.Controlador.ControladorVistaEnCorreo;
import com.mycompany.simercandetc.Controlador.ControladorVistaPlantilla;
import com.mycompany.simercandetc.Dao.EnviarCorreoDao;
import com.mycompany.simercandetc.Modelo.Asesor;
import com.mycompany.simercandetc.Modelo.Contacto;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.activation.DataHandler;
import javax.activation.FileDataSource;
import javax.mail.BodyPart;
import javax.mail.MessagingException;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMultipart;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Admin
 */
public class VistaDesCorreo extends javax.swing.JFrame {

    /**
     * Creates new form VistaDesCorreo
     */
    public VistaDesCorreo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jtAsunto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtDescrip = new javax.swing.JTextArea();
        btnCancelar = new javax.swing.JButton();
        btnEnviarCorreo = new javax.swing.JButton();
        txtIdU = new javax.swing.JTextField();
        txtFila = new javax.swing.JTextField();
        cmbPrograma = new javax.swing.JComboBox<>();
        btnRuta = new javax.swing.JButton();
        jtRuta = new javax.swing.JTextField();
        cmbAd = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 119, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, -40, -1, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel3.setText("ASUNTO:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, -1, -1));
        jPanel2.add(jtAsunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 610, -1));

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel4.setText("DESCRIPCION:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, -1, -1));

        jtDescrip.setColumns(20);
        jtDescrip.setRows(5);
        jScrollPane1.setViewportView(jtDescrip);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 610, 180));

        btnCancelar.setBackground(new java.awt.Color(204, 0, 0));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 460, 130, -1));

        btnEnviarCorreo.setBackground(new java.awt.Color(0, 255, 0));
        btnEnviarCorreo.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnEnviarCorreo.setForeground(new java.awt.Color(255, 255, 255));
        btnEnviarCorreo.setText("ENVIAR");
        btnEnviarCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarCorreoActionPerformed(evt);
            }
        });
        jPanel2.add(btnEnviarCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 460, 130, -1));
        jPanel2.add(txtIdU, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 143, 70, -1));
        jPanel2.add(txtFila, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 184, 70, -1));

        cmbPrograma.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cmbPrograma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PROGRAMA", " ", "INGENIERIA DE SOFTWARE", "DISEÑO GRAFICO", "DISEÑO DE MODAS", "ADMINISTRACION FINANCIERA", "NEGOCIOS INTERNACIONALES", "LOGISTICA EMPRESARIAL", "HOTELERIA Y TURISMO" }));
        jPanel2.add(cmbPrograma, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 230, 20));

        btnRuta.setText("....");
        btnRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRutaActionPerformed(evt);
            }
        });
        jPanel2.add(btnRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 460, -1, -1));
        jPanel2.add(jtRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 460, 300, -1));

        cmbAd.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cmbAd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No", "Si", " " }));
        cmbAd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAdActionPerformed(evt);
            }
        });
        jPanel2.add(cmbAd, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 90, -1));

        jLabel1.setText("USAR PLANTILLA:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 120, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        jtAsunto.setText("");
        jtDescrip.setText("");

        String idU = txtIdU.getText();
        ControladorVistaEnCorreo ctrEnCorreo = new ControladorVistaEnCorreo();
        ctrEnCorreo.mostrar(idU);
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnEnviarCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarCorreoActionPerformed
        String asunto = jtAsunto.getText();
        String descripcion = jtDescrip.getText();
        String prgm = cmbPrograma.getSelectedItem().toString();
        String ruta = jtRuta.getText();
        String adjuntar = cmbAd.getSelectedItem().toString();

        String idU = txtIdU.getText();
        String idF = txtFila.getText();

        String correoEmisor = "";
        String correoReceptor = "";
        String contraseñaCorreo = "";

        int c = JOptionPane.showConfirmDialog(null, "Enviar Correo? ", "Confirmacion", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);

        if (c == 0) {
            EnviarCorreoDao enCoDao = new EnviarCorreoDao();
            List<Asesor> lista = enCoDao.correoE(idU);

            if (idF.equals("todos")) {

                for (int i = 0; i < lista.size(); i++) {
                    correoEmisor = lista.get(i).getCorreo();
                    contraseñaCorreo = lista.get(i).getContraseña();

                }

                List<Contacto> listaC = enCoDao.correoTodos(prgm);

                String mensaje = "";
                int cont = 0;
                int nEl = listaC.size();
                String nombre = "";
                for (int i = 0; i < listaC.size(); i++) {
                    MimeMultipart partes = new MimeMultipart();

                    correoReceptor = listaC.get(i).getCorreo();
                    nombre = listaC.get(i).getNombre();
                    mensaje = "HOLA <b>" + nombre + "</b><br><br><br>" + descripcion + "<br><br>";
                    BodyPart archivo = new MimeBodyPart();
                    BodyPart texto = new MimeBodyPart();
                    System.out.println(mensaje);

                    try {
                        texto.setContent(mensaje, "text/html");
                        archivo.setDataHandler(new DataHandler(new FileDataSource(ruta)));

                        partes.addBodyPart(texto);
                        partes.addBodyPart(archivo);

                    } catch (MessagingException ex) {
                        Logger.getLogger(VistaDesCorreo.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    ControladorVistaDesCorreo ctrlDesCorreo = new ControladorVistaDesCorreo();
                    ctrlDesCorreo.enviarCorreo(asunto, partes, correoEmisor, correoReceptor, contraseñaCorreo,adjuntar,mensaje);
                    System.out.println(correoReceptor);
                    nombre = "";
                    //cont+=1;
                    //JOptionPane.showMessageDialog(null, "Enviando....."+cont+" de "+nEl+".\n\n Espere por favor");
                }
                JOptionPane.showMessageDialog(null, "Correo enviado");

            } else {
                List<Contacto> listaC = enCoDao.correoR(idF);
                String mensaje = "";

                for (int i = 0; i < lista.size(); i++) {
                    correoEmisor = lista.get(i).getCorreo();
                    contraseñaCorreo = lista.get(i).getContraseña();

                }
                for (int i = 0; i < listaC.size(); i++) {
                    MimeMultipart partes = new MimeMultipart();
                    String nombre = "";
                    correoReceptor = listaC.get(i).getCorreo();
                    nombre = listaC.get(i).getNombre();
                    mensaje = "HOLA <b>" + nombre + "</b><br><br><br>" + descripcion + "<br><br>";
                    BodyPart texto = new MimeBodyPart();
                    BodyPart archivo = new MimeBodyPart();

                    try {
                        texto.setContent(mensaje, "text/html");
                        archivo.setDataHandler(new DataHandler(new FileDataSource(ruta)));

                        partes.addBodyPart(texto);
                        partes.addBodyPart(archivo);

                    } catch (MessagingException ex) {
                        Logger.getLogger(VistaDesCorreo.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    ControladorVistaDesCorreo ctrlDesCorreo = new ControladorVistaDesCorreo();

                    ctrlDesCorreo.enviarCorreo(asunto, partes, correoEmisor, correoReceptor, contraseñaCorreo,adjuntar,mensaje);
                    System.out.println(texto);

                }

                JOptionPane.showMessageDialog(null, "Correo enviado");
            }
        }

        jtAsunto.setText("");
        jtDescrip.setText("");
        jtRuta.setText("");
    }//GEN-LAST:event_btnEnviarCorreoActionPerformed

    private void btnRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRutaActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);

        FileNameExtensionFilter texFilter = new FileNameExtensionFilter("archivos(*.txt)", "txt");
        fileChooser.setFileFilter(texFilter);

        int result = fileChooser.showOpenDialog(this);

        if (result != JFileChooser.CANCEL_OPTION) {

            File fileName = fileChooser.getSelectedFile();

            if ((fileName == null) || (fileName.getName().equals(""))) {
                jtRuta.setText("...");
            } else {
                jtRuta.setText(fileName.getAbsolutePath());
            }
        }
    }//GEN-LAST:event_btnRutaActionPerformed

    private void cmbAdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAdActionPerformed
        String adjuntar = cmbAd.getSelectedItem().toString();

        if (adjuntar.equals("No")) {
            jtRuta.setVisible(false);
            btnRuta.setVisible(false);
        } else {
            jtRuta.setVisible(true);
            btnRuta.setVisible(true);
        }
    }//GEN-LAST:event_cmbAdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaDesCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaDesCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaDesCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaDesCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaDesCorreo().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCancelar;
    public javax.swing.JButton btnEnviarCorreo;
    public javax.swing.JButton btnRuta;
    private javax.swing.JComboBox<String> cmbAd;
    public javax.swing.JComboBox<String> cmbPrograma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField jtAsunto;
    public javax.swing.JTextArea jtDescrip;
    public javax.swing.JTextField jtRuta;
    public javax.swing.JTextField txtFila;
    public javax.swing.JTextField txtIdU;
    // End of variables declaration//GEN-END:variables
}
